import { HttpMethodsEnum } from './http-methods';
import { KeyValuePair } from './key-value-pair';

export class DataRequest {
   
    private _route: string[]; // the route of the url.
    private _params: KeyValuePair[];  // the params to include in the url.
    private _baseUrl: string;
    private _modelStateName: string;
    private _body: any = null;    
    private _url: string = null; // the constructed url.   
    private _requestType: HttpMethodsEnum;    
    private _chainedRequest: (resp: any) => DataRequest = null;  // create a request after this one is completed
    
    /** get the request type asociated with this provider. */
    get requestType(): HttpMethodsEnum { return this._requestType }

    /** get the request body or null if is not available. */
    get body(): any { return this._body }
    
    /** get the url generated by this provider */
    get url(): string {

        if (!this._url) {
            //create the url
            let url = this._route.join('/');

            let parsedParams: string[] = [];
            this._params.forEach((v) => parsedParams.push([v.name, v.value].join('=')));

            if (parsedParams.length > 0) this._url = encodeURI(url + '?' + parsedParams.join('&'));
            else this._url = encodeURI(url);
        }

        return this._url;
    }

    /** get the unique name of the entity */
    get modelStateName() { return this._modelStateName; }

    /** get the request to be executed after or null if there is not any. */
    get chainedRequest() { return this._chainedRequest; }

    /** get the base url of this request */
    get baseUrl() { return this._baseUrl; }

    constructor(modelStateName: string, baseUrl: string, requestType: HttpMethodsEnum) {       
        this._baseUrl = baseUrl;
        this._modelStateName = modelStateName;
        this._requestType = requestType;
    }
   
    /**
     * add a path param to the url.
     * @param param the param to add to the url.
     */
    at(param: string): DataRequest {
        this._route.push(param);
        return this;
    }

    /**
     * add body to the request (only valid for POST and PUT requests)
     * @param body the body to add
     */
    withBody(body: any): DataRequest {
        if (this._requestType != 'POST' && this._requestType != 'PUT' && this._requestType != 'PATCH')
            throw "request body is only valid for POST, PATCH and PUT requests.";

        if (this._body != null)
            throw "request body can only be assigned one time.";

        this._body = body;
        return this;
    }

    withBaseUrl(baseUrl: string) {
        this._baseUrl = baseUrl;
        return this;
    }

    then(req: (resp: any) => DataRequest) {
        this._chainedRequest = req;
        return this;
    }
}
