import { HttpMethodsEnum } from './http-methods';
import { KeyValuePair } from './key-value-pair';

/**
 * represent an http request.
 */
export class RequestProvider {

    // the route of the url.
    private route: string[];

    // the params to include in the url.
    private params: KeyValuePair[];

    // base url of the request.
    private _baseUrl: string;

    private _uniqueName: string;

    // the request body.
    private _body: any = null;

    // the constructed url.
    private _url: string = null;

    // the request type.
    private _requestType: HttpMethodsEnum;


    // create a request after this one is completed
    private _chainedRequest: (resp: any) => RequestProvider = null;

    /** get the request type asociated with this provider. */
    get requestType(): HttpMethodsEnum {
        return this._requestType;
    }

    /** get the request body or null if is not available. */
    get body(): any { return this._body; }

    
    /** get the url generated by this provider */
    get url(): string {

        if (!this._url) {
            //create the url
            let url = this.route.join('/');
            let parsedParams: string[] = [];

            this.params.forEach((v) => {
                parsedParams.push([v.name, v.value].join('='));
            });

            if (parsedParams.length > 0)
                this._url = encodeURI(url + '?' + parsedParams.join('&'));
            else
                this._url = encodeURI(url);
        }

        return this._url;

    }

    /** get the unique name of the entity */
    get uniqueName() { return this._uniqueName; }

    /** get the request to be executed after or null if there is not any. */
    get chainedRequest() { return this._chainedRequest; }

    /** get the base url of this request */
    get baseUrl() { return this._baseUrl; }

    constructor(uniqueName: string, baseUrl: string, requestType: HttpMethodsEnum) { 
        this._baseUrl = baseUrl;
        this._uniqueName = uniqueName;
        this._requestType = requestType;
    }
   
    /**
     * add a path param to the url.
     * @param param the param to add to the url.
     */
    at(param: string): RequestProvider {
        this.route = this.route.concat(param);
        return this;
    }

    /**
     * add body to the request (only valid for POST and PUT requests)
     * @param body the body to add
     */
    withBody(body: any): RequestProvider {
        if (this._requestType != 'POST' && this._requestType != 'PUT' && this._requestType != 'PATCH')
            throw "request body is only valid for POST, PATCH and PUT requests.";

        if (this._body != null)
            throw "request body can only be assigned one time.";

        this._body = body;
        return this;
    }

    withBaseUrl(baseUrl: string) {
        this._baseUrl = baseUrl;
        return this;
    }

    then(req: (resp: any) => RequestProvider) {
        this._chainedRequest = req;
        return this;
    }
}
